export const SET_ACTIONS = {
  id: "SET_ID",
  continuous: "SET_CONTINUOUS",
  prepare: "SET_PREPARE",
  prepareMinutes: "SET_PREPARE_MINUTES",
  reps: "SET_REPS",
  work: "SET_WORK",
  workMinutes: "SET_WORK_MINUTES",
  rest: "SET_REST",
  restMinutes: "SET_REST_MINUTES",
  sets: "SET_SETS",
  break: "SET_BREAK",
  breakMinutes: "SET_BREAK_MINUTES",
  workout: "SET_WORKOUT",
  title: "SET_TITLE",
  reset: "RESET_WORKOUT",
  import: "IMPORT_WORKOUTS",
  userId: "SET_USER_ID",
  userGivenName: "SET_USER_GIVEN_NAME",
  userEmail: "SET_USER_EMAIL",
  userLogin: "SET_USER_LOGIN",
  userLogout: "SET_USER_LOGOUT"
}
